server:
  port: 9000

euraka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceURL:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/